<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-03 15:10

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.2.11 on 2026-02-09 12:24

import django.db.models.deletion
import django.utils.timezone
>>>>>>> 35b99e54e67e3aa1ffd73e07756b09f25fa2da05
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 35b99e54e67e3aa1ffd73e07756b09f25fa2da05
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
=======
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('body', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='new/images')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PU', 'Published')], default='DF', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'ordering': ['-publish_time'],
            },
        ),
>>>>>>> 35b99e54e67e3aa1ffd73e07756b09f25fa2da05
    ]
